### ISSUE TITLE
Update for vue 3

### ISSUE THREAD

**Issue by dacoto** [danielstgt/svg-vue#1]
The new version of vue 3 has already been released, are there plans to make this plugin compatible?

**Comment by danielstgt** [comment]
Yes, as soon as Laravel Mix 6 is out of beta. Vue 3 isn't supported with the current Laravel Mix 5 version.

**Comment by dacoto** [comment]
https://github.com/JeffreyWay/laravel-mix/releases/tag/v6.0.0

**Comment by danielstgt** [comment]
Vue 3 support has been tagged in [Laravel Mix SVG Vue](https://github.com/danielstgt/laravel-mix-svg-vue) v0.3.0.

To upgrade, run:

```sh
npm install laravel-mix-svg-vue
```

Or if you prefer yarn:

```sh
yarn add laravel-mix-svg-vue
```

**Comment by dacoto** [comment]
thank you so much, good job!
